# Generated by Django 4.2.2 on 2023-08-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shop.cartmodel'),
        ),
        migrations.AddField(
            model_name='users',
            name='love',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='love', to='shop.lovemodel'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
