# Generated by Django 4.2.2 on 2023-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_users_cart_users_love_alter_users_id'),
    ]

    operations = [
    ]
