# Generated by Django 4.2.2 on 2023-09-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='users',
            name='love',
        ),
    ]
