# Generated by Django 4.2.2 on 2023-08-29 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_goodmodule_have_goodmodule_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('pay_method', models.IntegerField(choices=[(1, 'alipay'), (2, 'cash')], default=1)),
                ('pay_status', models.IntegerField(choices=[(1, '待支付 '), (2, '已支付'), (3, '已取消')], default=1)),
                ('total_count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='shop.goodmodule')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orders',
                'verbose_name_plural': 'orders',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.orderinfo')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payment',
                'db_table': 't_payment',
            },
        ),
    ]
