# Generated by Django 4.2.2 on 2023-08-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
    ]
