# Generated by Django 4.2.2 on 2023-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230829_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(verbose_name='支付总金额'),
        ),
    ]
