# Generated by Django 4.2.2 on 2023-09-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_alter_goodmodule_img_url'),
        ('payment', '0003_alter_orderinfo_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='shop.goodmodule'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to=settings.AUTH_USER_MODEL),
        ),
    ]
