# Generated by Django 4.2.2 on 2023-08-27 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField(verbose_name='goods name')),
                ('goods_name', models.CharField(max_length=15, verbose_name='goods name')),
                ('goods_price', models.FloatField(max_length=6, verbose_name='goods price')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'cart',
                'db_table': 't_cart',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='GoodModule',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('comment', models.TextField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=5)),
                ('img_url', models.ImageField(upload_to='', verbose_name='first image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='shop.categorymodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='LoveModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField(verbose_name='goods name')),
                ('goods_name', models.CharField(max_length=15, verbose_name='goods name')),
                ('goods_price', models.FloatField(max_length=6, verbose_name='goods price')),
            ],
            options={
                'verbose_name': 'love',
                'verbose_name_plural': 'love',
                'db_table': 't_love',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('inner_img', models.ImageField(upload_to='', verbose_name='inner image')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='shop.goodmodule')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'image',
                'db_table': 't_image',
            },
        ),
    ]
