# Generated by Django 4.2.2 on 2023-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_goodmodule_have_goodmodule_status'),
    ]

    operations = [
    ]
