# Generated by Django 4.2.2 on 2023-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230829_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
