# Generated by Django 4.2.2 on 2023-09-02 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_alter_goodmodule_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lovemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='love', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='goods_id',
            field=models.IntegerField(verbose_name='goods id'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lovemodel',
            name='goods_id',
            field=models.IntegerField(verbose_name='goods id'),
        ),
        migrations.AlterField(
            model_name='lovemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
