# Generated by Django 4.2.2 on 2023-09-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_goodmodule_comment_alter_goodmodule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='goods name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodmodule',
            name='comment',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodmodule',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lovemodel',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='goods name'),
        ),
    ]
